#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_register:
  resource: ../src/Controller/RegistrationController.php
  type: annotation

app_login:
  resource: ../src/Controller/UserController.php
  type: annotation
